sudo: false
language: python
python:
  - "3.8"
install:
  - pip install bikeshed
  - bikeshed update
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "7955d0063fe8"
  - COMMIT_AUTHOR_EMAIL: "jaffathecake@gmail.com"
